### ISSUE TITLE
Недочеты 3 лабораторной

### ISSUE THREAD

**Issue by jovfer** [AlenaErsh/C-3#1]
Посмотрел внимательно на данную лабу - увидил причину проблемы, когда при текущем деструкторе программа в конце исполнения может упасть.
В текущем коде не определен конструктор копирования и используются обычные указатели, поэтому происходит следующее:
* в функции `TestUser` создается на стеке объект очереди, в его конструкторе выделяется память под внутренний массив
* при вызове `Menu` происходит примитивное копирование объекта, т.е. в копию помещается указатель на внутренний массив оригинала. Более того, эта фукнция зачем-то написана рекурсивно, поэтому таких копий будет много
* когда заканчивается время жизни любой из копий, вызывается деструктор и очищается память из-под внутреннего массива, далее undefined behavior - может происходить все что угодно. А когда вызовется деструктор для другой копии или оригинала - почти гарантировано падение программы.
Надо это исправить, жалко что я сразу не увидел этого копирования еще 2 пары назад.

- [x] либо изучите тему конструктора копирования и реализуйте его
либо изучите тему "умных указателей" появившихся в стандарте C++11 (сложнее, дольше, но полезнее)
- [x] избавьтесь от рекурсии в функции `Menu`

**Comment by AlenaErsh** [comment]
Убрала рекурсию в функции Menu. И пошла всё-таки, к своему стыду, по пути наименьшего сопротивления, и добавила конструктор копирования.
